name: CI/CD > Production Site 

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy React App
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/github
          chmod 600 ~/.ssh/github
          cat >>~/.ssh/config <<END
          Host target
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/github
            LogLevel ERROR
            StrictHostKeyChecking no
          END

      - name: Deploy to VPS
        run: |
          ssh target "
            set -e
            cd /var/www/dev/ghosttransfer.tech/html || exit 1
            git pull origin main
            npm ci
            npm run build
            cp -r ./dist/* /var/www/dev/ghosttransfer.tech/html/dist/
            nginx -t && systemctl reload nginx
          "
